version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$PASSWORD
      - MYSQL_DATABASE=$DATABASE
    ports:
      - $PORT:$PORT
    volumes:
      - mysql:/var/lib/
    networks:
      - jira
  app:
    depends_on:
      - mysql
    build: .
    container_name: jira-be
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      - USERNAME=$USERNAME
      - PASSWORD=$PASSWORD
      - DATABASE=$DATABASE
      - PORT=$PORT
      - DIALECT=$DIALECT
      - SECRET_KEY=$SECRET_KEY
      - HOST=mysql
      - S3_BUCKET_NAME=$S3_BUCKET_NAME
      - S3_DOMAIN_NAME=$S3_DOMAIN_NAME
      - S3_ACCESS_KEY_ID=$S3_ACCESS_KEY_ID
      - S3_SECRET_KEY=$S3_SECRET_KEY
    networks:
      - jira

volumes:
  mysql:
    driver: local

networks:
  jira: